apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quick-note-postgres-pvc
  namespace: quick-note
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-note-postgres
  namespace: quick-note
  labels:
    app: quick-note-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-note-postgres
  template:
    metadata:
      labels:
        app: quick-note-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: quick-note-db
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "duylong", "-d", "quicknote"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "duylong", "-d", "quicknote"]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: quick-note-postgres-pvc
        - name: init-sql
          configMap:
            name: quick-note-sql
---
apiVersion: v1
kind: Service
metadata:
  name: quick-note-postgres
  namespace: quick-note
spec:
  selector:
    app: quick-note-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
